Find the decision for multiline iconed label (@taskany/bricks#863)
taskany-inc/icons pull request #123
Opened 2024-03-07 15:31 UTC by LamaEats

Fix of align icon in wrapper

## PR includes

- [x] Bug Fix

## Related issues

Related issues https://github.com/taskany-inc/bricks/issues/863

2024-03-07 15:32 UTC, LamaEats commented
/canary

2024-03-11 09:25 UTC, DenisVorop approved these changes

2024-03-11 09:41 UTC, awinogradov requested changes
<img width="655" alt="image" src="https://github.com/taskany-inc/icons/assets/982072/f1d74a30-03ed-4f1d-89d2-7cd299aa42b1">

2024-03-11 09:53 UTC, awinogradov approved these changes

2024-03-11 12:08 UTC, merged